apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: app
spec:
  environments:
    - name: prod
      build:
        from: main
  components:
    - name: app
      dockerfilename: app.Dockerfile
      publicPort: http
      ports:
      - name: http
        port: 3000
  spec:
    dnsAppAlias:
      environment: prod
      component: app
